/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import src.proyecto01.Marca;

/**
 *
 * @author Enzo Morales
 */
public class VentanaAgregarEliminarMarca extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregarEliminarMarca
     */
    public VentanaAgregarEliminarMarca() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelFondoInstrucciones = new javax.swing.JLabel();
        jLabelAgregar = new javax.swing.JLabel();
        jLabelDivisión = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldCategoria = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMarcas = new javax.swing.JList<>();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("Registrar o eliminar marca");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion1.setText("Aquí puede agregar o eliminar marcas. Para agregar por favor ingrese los datos solicitados");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion2.setText("(lado izquierdo), o bien seleccione la marca que desea eliminar (lado derecho).");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 550, -1));

        jLabelFondoInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoInstrucciones.setOpaque(true);
        getContentPane().add(jLabelFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 590, 90));

        jLabelAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAgregar.setText("Agregar");
        getContentPane().add(jLabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabelDivisión.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDivisión.setOpaque(true);
        getContentPane().add(jLabelDivisión, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 100, 3, 260));

        jLabelEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEliminar.setText("Eliminar");
        getContentPane().add(jLabelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCategoria.setText("Categoría:");
        getContentPane().add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jTextFieldCategoria.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCategoria.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, -1));

        jButtonAgregar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAgregar.setText("Agregar marca");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jListMarcas.setBackground(new java.awt.Color(204, 204, 204));
        jListMarcas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListMarcas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListMarcas.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jListMarcas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 250, 150));

        jButtonEliminar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(204, 204, 204));
        jButtonEliminar.setText("Eliminar marca");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 340, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(0, 173, 181));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new VentanaMenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String categoria = jTextFieldCategoria.getText();
        if (categoria.length() != 0) {
            Marca marcaNueva = new Marca(categoria);
            cargarListBox();
            JOptionPane.showMessageDialog(null, "La marca ha sido registrada correctamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegúrese de llenar el campo de texto de categoría.", "Error: Campo vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String valorSeleccionado = jListMarcas.getSelectedValue();
        if (valorSeleccionado != null) {
            int marcaSeleccionada = jListMarcas.getSelectedIndex();
            Marca marcaTemporal = new Marca();
            ArrayList<Marca> listaMarcas = marcaTemporal.getListaMarcas();
            listaMarcas.remove(marcaSeleccionada);
            cargarListBox();
            JOptionPane.showMessageDialog(null, "La marca ha sido eliminada correctamente.", "Eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Para poder eliminar una marca, debe escoger una antes.", "Error: Marca no seleccionada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    public void cargarListBox () {
        Marca marcaTemporal = new Marca();
        ArrayList<Marca> listaMarcas = marcaTemporal.getListaMarcas();
        DefaultListModel modelo = new DefaultListModel();
        for(int cont = 0; cont<listaMarcas.size(); cont++){
            modelo.addElement((cont+1)+") "+listaMarcas.get(cont).getCategoria());
        }
        jListMarcas.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDivisión;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoInstrucciones;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListMarcas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCategoria;
    // End of variables declaration//GEN-END:variables
}
