/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.JOptionPane;
import src.proyecto01.Cliente;

/**
 *
 * @author Enzo Morales
 */
public class VentanaRegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistrarEmpleado
     */
    public VentanaRegistrarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelFondoInstrucciones = new javax.swing.JLabel();
        jLabelNombreApellidos = new javax.swing.JLabel();
        jLabelIdentificacion = new javax.swing.JLabel();
        jLabelTipoIdentificacion = new javax.swing.JLabel();
        jLabelProvincia = new javax.swing.JLabel();
        jLabelFechaCumpleannos = new javax.swing.JLabel();
        jLabelCanton = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jButtonAgregarCliente = new javax.swing.JButton();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldProvincia = new javax.swing.JTextField();
        jTextFieldTipoIdentificacion = new javax.swing.JTextField();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldNombreApellidos = new javax.swing.JTextField();
        jFormattedTextFieldFechaCumpleannos = new javax.swing.JFormattedTextField();
        jButtonVolver = new javax.swing.JButton();
        jTextFieldCanton = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("Registrar cliente");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion1.setText("Aquí puede registrar nuevos clientes, para ello, por favor ingrese los");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion2.setText("datos solicitados a continuación.");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelFondoInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoInstrucciones.setOpaque(true);
        getContentPane().add(jLabelFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 10, 447, 90));

        jLabelNombreApellidos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelNombreApellidos.setText("Nombre y apellidos:");
        getContentPane().add(jLabelNombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabelIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelIdentificacion.setText("Identificación:");
        getContentPane().add(jLabelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 170, -1, -1));

        jLabelTipoIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelTipoIdentificacion.setText("Tipo de identificación:");
        getContentPane().add(jLabelTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 210, -1, -1));

        jLabelProvincia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelProvincia.setText("Provincia:");
        getContentPane().add(jLabelProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 250, -1, -1));

        jLabelFechaCumpleannos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelFechaCumpleannos.setText("Fecha de cumpleaños:");
        getContentPane().add(jLabelFechaCumpleannos, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 330, -1, -1));

        jLabelCanton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCanton.setText("Cantón:");
        getContentPane().add(jLabelCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 370, -1, -1));

        jLabelCorreoElectronico.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCorreoElectronico.setText("Correo electrónico:");
        getContentPane().add(jLabelCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jButtonAgregarCliente.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarCliente.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonAgregarCliente.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAgregarCliente.setText("Registrar cliente");
        jButtonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 200, -1));
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 200, -1));
        getContentPane().add(jTextFieldProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 200, -1));
        getContentPane().add(jTextFieldTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 200, -1));
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 200, -1));
        getContentPane().add(jTextFieldNombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 200, -1));

        try {
            jFormattedTextFieldFechaCumpleannos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldFechaCumpleannos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 200, -1));

        jButtonVolver.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 490, -1, -1));
        getContentPane().add(jTextFieldCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 200, -1));

        jLabelFondo.setBackground(new java.awt.Color(0, 173, 181));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarClienteActionPerformed
        String nombreApellidos = jTextFieldNombreApellidos.getText();
        String id = jTextFieldIdentificacion.getText();
        String tipoId = jTextFieldTipoIdentificacion.getText();
        String provincia = jTextFieldProvincia.getText();
        String canton = jTextFieldCanton.getText();
        String fechaCumpleannos = jFormattedTextFieldFechaCumpleannos.getText();
        String telefono = jTextFieldTelefono.getText();
        String correo = jTextFieldCorreo.getText();;
        if (nombreApellidos.length() != 0 && id.length() != 0 && tipoId.length() != 0 && provincia.length() != 0 && canton.length() != 0 && !fechaCumpleannos.equals("  /  /  ") && telefono.length() != 0 && correo.length() != 0) {
           Cliente nuevoCliente = new Cliente(nombreApellidos, id, tipoId, provincia, canton, fechaCumpleannos, telefono, correo);
           JOptionPane.showMessageDialog(null, "El cliente ha sido registrado correctamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegúrese de llenar todos los campos de texto solicitados.", "Error: Campo vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarClienteActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new VentanaMenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarCliente;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaCumpleannos;
    private javax.swing.JLabel jLabelCanton;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelFechaCumpleannos;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoInstrucciones;
    private javax.swing.JLabel jLabelIdentificacion;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelNombreApellidos;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoIdentificacion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCanton;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombreApellidos;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTipoIdentificacion;
    // End of variables declaration//GEN-END:variables
}
