/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import javax.swing.JOptionPane;
import src.proyecto01.Empleado;

/**
 *
 * @author Enzo Morales
 */
public class VentanaRegistrarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistrarEmpleado
     */
    public VentanaRegistrarEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelInstruccion3 = new javax.swing.JLabel();
        jLabelInstruccion4 = new javax.swing.JLabel();
        jLabelFondoInstrucciones = new javax.swing.JLabel();
        jLabelNombreApellidos = new javax.swing.JLabel();
        jLabelIdentificacion = new javax.swing.JLabel();
        jLabelTipoIdentificacion = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelFechaCumpleannos = new javax.swing.JLabel();
        jLabelFechaIngreso = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenna = new javax.swing.JLabel();
        jLabelConfirmacion = new javax.swing.JLabel();
        jButtonAgregarEmpleado = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldRol = new javax.swing.JTextField();
        jTextFieldTipoIdentificacion = new javax.swing.JTextField();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldNombreApellidos = new javax.swing.JTextField();
        jFormattedTextFieldFechaIngreso = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFechaCumpleannos = new javax.swing.JFormattedTextField();
        jLabelFormato1 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jPasswordFieldContrasenna = new javax.swing.JPasswordField();
        jPasswordFieldConfirmacionContrasenna = new javax.swing.JPasswordField();
        jLabelCampoUsuario = new javax.swing.JLabel();
        jLabelFondoOpcional = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("Registrar empleado del taller");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion1.setText("Aquí puede agregar nuevos empleados al taller, para ello, por favor");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion2.setText("Ingrese los datos solicitados a continuación. En caso de que este");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelInstruccion3.setBackground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion3.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion3.setText("nuevo empleado no vaya a utilizar el sistema, puede omitir los cam-");
        getContentPane().add(jLabelInstruccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabelInstruccion4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion4.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion4.setText("pos de nombre de usuario, contraseña y confirmación de contraseña.");
        getContentPane().add(jLabelInstruccion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabelFondoInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoInstrucciones.setOpaque(true);
        getContentPane().add(jLabelFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 10, 447, 140));

        jLabelNombreApellidos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelNombreApellidos.setText("Nombre y apellidos:");
        getContentPane().add(jLabelNombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabelIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelIdentificacion.setText("Identificación:");
        getContentPane().add(jLabelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabelTipoIdentificacion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTipoIdentificacion.setText("Tipo de identificación:");
        getContentPane().add(jLabelTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabelRol.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelRol.setText("Rol:");
        getContentPane().add(jLabelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabelFechaCumpleannos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelFechaCumpleannos.setText("Fecha de cumpleaños:");
        getContentPane().add(jLabelFechaCumpleannos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabelFechaIngreso.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelFechaIngreso.setText("Fecha de ingreso:");
        getContentPane().add(jLabelFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        getContentPane().add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabelCorreoElectronico.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelCorreoElectronico.setText("Correo electrónico:");
        getContentPane().add(jLabelCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        jLabelContrasenna.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelContrasenna.setText("Contraseña:");
        getContentPane().add(jLabelContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabelConfirmacion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelConfirmacion.setText("Confirmación de contraseña:");
        getContentPane().add(jLabelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jButtonAgregarEmpleado.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonAgregarEmpleado.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAgregarEmpleado.setText("Registrar empleado");
        jButtonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 593, -1, -1));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, -1));
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 200, -1));
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 200, -1));
        getContentPane().add(jTextFieldRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 200, -1));
        getContentPane().add(jTextFieldTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, -1));
        getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 200, -1));
        getContentPane().add(jTextFieldNombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 200, -1));

        try {
            jFormattedTextFieldFechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 200, -1));

        try {
            jFormattedTextFieldFechaCumpleannos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldFechaCumpleannos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 200, -1));

        jLabelFormato1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelFormato1.setText("(dd/mm/aa)");
        getContentPane().add(jLabelFormato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 343, 70, -1));

        jButtonVolver.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 610, -1, -1));
        getContentPane().add(jPasswordFieldContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 200, -1));
        getContentPane().add(jPasswordFieldConfirmacionContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 200, -1));

        jLabelCampoUsuario.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabelCampoUsuario.setText("Campos para el usuario");
        getContentPane().add(jLabelCampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 130, -1));

        jLabelFondoOpcional.setBackground(new java.awt.Color(204, 204, 204));
        jLabelFondoOpcional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondoOpcional.setOpaque(true);
        getContentPane().add(jLabelFondoOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 460, 170));

        jLabelFondo.setBackground(new java.awt.Color(0, 173, 181));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEmpleadoActionPerformed
        String nombreApellidos = jTextFieldNombreApellidos.getText();
        String id = jTextFieldIdentificacion.getText();
        String tipoId = jTextFieldTipoIdentificacion.getText();
        String rol = jTextFieldRol.getText();
        String fechaCumpleannos = jFormattedTextFieldFechaCumpleannos.getText();
        String fechaIngreso = jFormattedTextFieldFechaIngreso.getText();
        String telefono = jTextFieldTelefono.getText();
        String correo = jTextFieldCorreo.getText();
        String usuario = jTextFieldUsuario.getText();
        String contrasenna = jPasswordFieldContrasenna.getText();
        String confirmacionContrasenna = jPasswordFieldConfirmacionContrasenna.getText();
        if (nombreApellidos.length() != 0 && id.length() != 0 && tipoId.length() != 0 && rol.length() != 0 && !fechaCumpleannos.equals("  /  /  ") && !fechaIngreso.equals("  /  /  ") && telefono.length() != 0 && correo.length() != 0) {
           if (usuario.length() != 0 && contrasenna.length() != 0 && confirmacionContrasenna.length() != 0) {
               if (contrasenna.equals(confirmacionContrasenna)) {
                   Empleado empleadoNuevo = new Empleado(rol, fechaIngreso, nombreApellidos, id, tipoId, fechaCumpleannos, telefono, correo, usuario, contrasenna);
                   JOptionPane.showMessageDialog(null, "El empleado y su usuario han sido registrados correctamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
               }else {
                    JOptionPane.showMessageDialog(null, "La contraseña no coincide con la confirmación de esta.", "Error: Contraseñas distintas", JOptionPane.ERROR_MESSAGE);
               }
           } else {
               Empleado empleadoNuevo = new Empleado(rol, fechaIngreso, nombreApellidos, id, tipoId, fechaCumpleannos, telefono, correo);
               JOptionPane.showMessageDialog(null, "El empleado ha sido registrado correctamente (sin un usuario).", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
           }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegúrese de llenar todos los campos de texto solicitados (exceptuando los de usuario si no desea crear uno).", "Error: Campo vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarEmpleadoActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new VentanaMenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarEmpleado;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaCumpleannos;
    private javax.swing.JFormattedTextField jFormattedTextFieldFechaIngreso;
    private javax.swing.JLabel jLabelCampoUsuario;
    private javax.swing.JLabel jLabelConfirmacion;
    private javax.swing.JLabel jLabelContrasenna;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelFechaCumpleannos;
    private javax.swing.JLabel jLabelFechaIngreso;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoInstrucciones;
    private javax.swing.JLabel jLabelFondoOpcional;
    private javax.swing.JLabel jLabelFormato1;
    private javax.swing.JLabel jLabelIdentificacion;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelInstruccion3;
    private javax.swing.JLabel jLabelInstruccion4;
    private javax.swing.JLabel jLabelNombreApellidos;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoIdentificacion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldConfirmacionContrasenna;
    private javax.swing.JPasswordField jPasswordFieldContrasenna;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombreApellidos;
    private javax.swing.JTextField jTextFieldRol;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTipoIdentificacion;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
