/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import src.proyecto01.Marca;
import src.proyecto01.Modelo;

/**
 *
 * @author Enzo Morales
 */
public class VentanaAgregarEliminarModelo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgregarEliminarModelo
     */
    public VentanaAgregarEliminarModelo() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListBox();
        cargarComboBoxMarcas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelFondoInstrucciones = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelPuertas = new javax.swing.JLabel();
        jLabelCombustible = new javax.swing.JLabel();
        jLabelTransmision = new javax.swing.JLabel();
        jButtonAgregarModelo = new javax.swing.JButton();
        jLabelDivisión = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jComboBoxMarcas = new javax.swing.JComboBox<>();
        jTextFieldCombustible = new javax.swing.JTextField();
        jComboBoxTransmision = new javax.swing.JComboBox<>();
        jTextFieldCantidadAsientos = new javax.swing.JTextField();
        jTextFieldCantidadPuertas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListModelos = new javax.swing.JList<>();
        jButtonEliminarMarca = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("Registrar o eliminar modelo");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion1.setText("Aquí puede agregar o eliminar modelos. Para agregar por favor ingrese los datos solicitados (lado izquierdo), o bien");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion2.setText("seleccione la marca que desea eliminar (lado derecho).");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, -1, -1));

        jLabelFondoInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoInstrucciones.setOpaque(true);
        getContentPane().add(jLabelFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 750, 90));

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelDescripcion.setText("Descripción modelo:");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelMarca.setText("Marca de vehículo:");
        getContentPane().add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 170, -1, -1));

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCantidad.setText("Cantidad de asientos:");
        getContentPane().add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 220, -1, -1));

        jLabelPuertas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPuertas.setText("Cantidad de puertas:");
        getContentPane().add(jLabelPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, -1, -1));

        jLabelCombustible.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelCombustible.setText("Combustible:");
        getContentPane().add(jLabelCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 320, -1, -1));

        jLabelTransmision.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelTransmision.setText("Transmisión:");
        getContentPane().add(jLabelTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 370, -1, -1));

        jButtonAgregarModelo.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAgregarModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregarModelo.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAgregarModelo.setText("Agregar modelo");
        jButtonAgregarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarModeloActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        jLabelDivisión.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDivisión.setOpaque(true);
        getContentPane().add(jLabelDivisión, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 98, 3, 375));

        jTextFieldDescripcion.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 25));

        jComboBoxMarcas.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxMarcas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No seleccionada" }));
        jComboBoxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 25));

        jTextFieldCombustible.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCombustible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCombustible.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, 25));

        jComboBoxTransmision.setBackground(new java.awt.Color(204, 204, 204));
        jComboBoxTransmision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxTransmision.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxTransmision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automático", "Manual" }));
        getContentPane().add(jComboBoxTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 170, 25));

        jTextFieldCantidadAsientos.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadAsientos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadAsientos.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldCantidadAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 170, 25));

        jTextFieldCantidadPuertas.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCantidadPuertas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCantidadPuertas.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jTextFieldCantidadPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 170, 25));

        jListModelos.setBackground(new java.awt.Color(204, 204, 204));
        jListModelos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListModelos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListModelos.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jListModelos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 360, 290));

        jButtonEliminarMarca.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEliminarMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminarMarca.setForeground(new java.awt.Color(204, 204, 204));
        jButtonEliminarMarca.setText("Eliminar marca");
        jButtonEliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 450, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(0, 173, 181));
        jLabelFondo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarMarcaActionPerformed
        String valorSeleccionado = jListModelos.getSelectedValue();
        if (valorSeleccionado != null) {
            int modeloSeleccionado = jListModelos.getSelectedIndex();
            Modelo modeloTemporal = new Modelo();
            ArrayList<Modelo> listaModelos = modeloTemporal.getListaModelos();
            listaModelos.remove(modeloSeleccionado);
            cargarListBox();
            JOptionPane.showMessageDialog(null, "El modelo ha sido eliminado correctamente.", "Eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Para poder eliminar un modelo, debe escoger uno antes.", "Error: Modelo no seleccionado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarMarcaActionPerformed

    private void jButtonAgregarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarModeloActionPerformed
        String descripcionModelo = jTextFieldDescripcion.getText();
        String marca = jComboBoxMarcas.getSelectedItem().toString();
        String cantidadAsientos = jTextFieldCantidadAsientos.getText();
        String cantidadPuertas = jTextFieldCantidadPuertas.getText();
        String combustible = jTextFieldCombustible.getText();
        String transmision = jComboBoxTransmision.getSelectedItem().toString();
        
        if (descripcionModelo.length() != 0 && !marca.equals("No seleccionada") && cantidadAsientos.length() != 0 && cantidadPuertas.length() != 0 && combustible.length() != 0) {
            Marca marcaTemporal = new Marca();
            ArrayList<Marca> listaMarcas = marcaTemporal.getListaMarcas();
            for(int cont = 0; cont<listaMarcas.size(); cont++){
                if (listaMarcas.get(cont).getCategoria().equals(marca)) {
                    marcaTemporal = listaMarcas.get(cont);
                }
            }
            
            Modelo modeloNuevo = new Modelo(descripcionModelo, marcaTemporal, cantidadAsientos, cantidadPuertas, combustible, transmision);
            cargarListBox();
            JOptionPane.showMessageDialog(null, "El modelo ha sido registrado correctamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegúrese de llenar todos los campos de texto solicitados (incluyento los combo box).", "Error: Campo vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarModeloActionPerformed

    private void jComboBoxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcasActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new VentanaMenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public void cargarComboBoxMarcas(){
        Marca marcaTemporal = new Marca();
        ArrayList<Marca> listaMarcas = marcaTemporal.getListaMarcas();
        for(int cont = 0; cont<listaMarcas.size(); cont++){
            jComboBoxMarcas.addItem(listaMarcas.get(cont).getCategoria());
        }
    }
    
    public void cargarListBox () {
        Modelo modeloTemporal = new Modelo();
        ArrayList<Modelo> listaModelos = modeloTemporal.getListaModelos();
        DefaultListModel modelo = new DefaultListModel();
        for(int cont = 0; cont<listaModelos.size(); cont++){
            modelo.addElement((cont+1)+") Descripción: " + listaModelos.get(cont).getDescripcion() +
                                    " - " + "Marca: " + listaModelos.get(cont).getMarca().getCategoria() +
                                    " - " + "Asientos: " + listaModelos.get(cont).getCantidadAsientos() + 
                                    " - " + "Puertas: " + listaModelos.get(cont).getCantidadPuertas() + 
                                    " - " + "Combustible: " + listaModelos.get(cont).getCombustible() + 
                                    " - " + "Transmisión: " + listaModelos.get(cont).getTransmision() + ".");
        }
        jListModelos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarModelo;
    private javax.swing.JButton jButtonEliminarMarca;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JComboBox<String> jComboBoxTransmision;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCombustible;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDivisión;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoInstrucciones;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelPuertas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTransmision;
    private javax.swing.JList<String> jListModelos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCantidadAsientos;
    private javax.swing.JTextField jTextFieldCantidadPuertas;
    private javax.swing.JTextField jTextFieldCombustible;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
