/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import src.proyecto01.Marca;
import src.proyecto01.Modelo;
import src.proyecto01.Vehiculo;

/**
 *
 * @author Enzo Morales
 */
public class VentanaRegistrarVehiculoCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistrarVehiculoCliente
     */
    public VentanaRegistrarVehiculoCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarComboBoxMarcas();
        cargarComboBoxModelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion = new javax.swing.JLabel();
        jLabelFondoInstrucciones = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelAnno = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldAnno = new javax.swing.JTextField();
        jComboBoxMarcas = new javax.swing.JComboBox<>();
        jComboBoxModelos = new javax.swing.JComboBox<>();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(280, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("Registrar vehículo del cliente");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabelInstruccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion.setText("Por favor ingrese los datos solicitados para poder registrar un vehículo");
        getContentPane().add(jLabelInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelFondoInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoInstrucciones.setOpaque(true);
        getContentPane().add(jLabelFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 460, 70));

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelModelo.setText("Modelo:");
        getContentPane().add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabelAnno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAnno.setText("Año:");
        getContentPane().add(jLabelAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jButtonRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(204, 204, 204));
        jButtonRegistrar.setText("Registrar Vehiculo");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));
        getContentPane().add(jTextFieldPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, -1));
        getContentPane().add(jTextFieldAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, -1));

        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No seleccionada" }));
        jComboBoxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, -1));

        jComboBoxModelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No seleccionado" }));
        getContentPane().add(jComboBoxModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, -1));

        jButtonVolver.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(204, 204, 204));
        jButtonVolver.setText("<--");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(0, 173, 181));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcasActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new VentanaMenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        String marca = jComboBoxMarcas.getSelectedItem().toString();
        String modelo = jComboBoxModelos.getSelectedItem().toString();
        String placa = jTextFieldPlaca.getText();
        String anno = jTextFieldAnno.getText();
        Marca marcaTemporal = new Marca();
        ArrayList<Marca> listaMarcas = marcaTemporal.getListaMarcas();
        for(int cont = 0; cont<listaMarcas.size(); cont++){
            if (listaMarcas.get(cont).getCategoria().equals(marca)) {
                marcaTemporal = listaMarcas.get(cont);
            }
        }
        
        Modelo ModeloTemporal = new Modelo();
        ArrayList<Modelo> listaModelos = ModeloTemporal.getListaModelos();
        for(int cont = 0; cont<listaModelos.size(); cont++){
            if (listaModelos.get(cont).getDescripcion().equals(modelo)) {
                ModeloTemporal = listaModelos.get(cont);
            }
        }
        
        Vehiculo vehiculoNuevo = new Vehiculo(marcaTemporal, ModeloTemporal, placa, anno);
        
        JOptionPane.showMessageDialog(null, "El vehiculo ha sido registrado correctamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    public void cargarComboBoxMarcas(){
        Marca marcaTemporal = new Marca();
        ArrayList<Marca> listaMarcas = marcaTemporal.getListaMarcas();
        for(int cont = 0; cont<listaMarcas.size(); cont++){
            jComboBoxMarcas.addItem(listaMarcas.get(cont).getCategoria());
        }
    }
    
    public void cargarComboBoxModelos(){
        Modelo ModeloTemporal = new Modelo();
        ArrayList<Modelo> listaModelos = ModeloTemporal.getListaModelos();
        for(int cont = 0; cont<listaModelos.size(); cont++){
            jComboBoxModelos.addItem(listaModelos.get(cont).getDescripcion());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JComboBox<String> jComboBoxModelos;
    private javax.swing.JLabel jLabelAnno;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoInstrucciones;
    private javax.swing.JLabel jLabelInstruccion;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldAnno;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
