/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica;

/**
 *
 * @author Enzo Morales
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenuPrincipal = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelFondoInstrucciones = new javax.swing.JLabel();
        jButtonReMarca = new javax.swing.JButton();
        jButtonReEmpleados = new javax.swing.JButton();
        jButtonReCliente = new javax.swing.JButton();
        jButtonModelo = new javax.swing.JButton();
        jButtonReVehiculo = new javax.swing.JButton();
        jButtonReServicio = new javax.swing.JButton();
        jButtonConsultarHistorial = new javax.swing.JButton();
        jButtonConsultarDetalle = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondoBotones = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMenuPrincipal.setForeground(new java.awt.Color(153, 153, 153));
        jLabelMenuPrincipal.setText("Menú principal");
        getContentPane().add(jLabelMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion1.setText("Bienvenido al sistema del taller mecánico y pintura. Por favor seleccione ");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInstruccion2.setText("la opción que desea ejecutar a continuación.");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabelFondoInstrucciones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoInstrucciones.setOpaque(true);
        getContentPane().add(jLabelFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 3, 480, 120));

        jButtonReMarca.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReMarca.setText("Registrar o eliminar marca");
        jButtonReMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 241, 30));

        jButtonReEmpleados.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReEmpleados.setText("Registrar empleado del taller");
        jButtonReEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 241, 30));

        jButtonReCliente.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReCliente.setText("Registrar cliente");
        jButtonReCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 250, 241, 30));

        jButtonModelo.setBackground(new java.awt.Color(153, 153, 153));
        jButtonModelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonModelo.setText("Registrar o eliminar modelo");
        jButtonModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModeloActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 190, 241, 30));

        jButtonReVehiculo.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReVehiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReVehiculo.setText("Registrar vehículo del cliente");
        jButtonReVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 241, 30));

        jButtonReServicio.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReServicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReServicio.setText("Registrar servicio del taller");
        getContentPane().add(jButtonReServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 310, 241, 30));

        jButtonConsultarHistorial.setBackground(new java.awt.Color(153, 153, 153));
        jButtonConsultarHistorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConsultarHistorial.setText("Consultar historial de pedidos");
        getContentPane().add(jButtonConsultarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 241, 30));

        jButtonConsultarDetalle.setBackground(new java.awt.Color(153, 153, 153));
        jButtonConsultarDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConsultarDetalle.setText("Consultar detalle de servicio");
        getContentPane().add(jButtonConsultarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 370, 241, 30));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Cerrar sesión");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, 25));

        jLabelFondoBotones.setBackground(new java.awt.Color(51, 51, 51));
        jLabelFondoBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondoBotones.setOpaque(true);
        getContentPane().add(jLabelFondoBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 540, 310));

        jLabelFondo.setBackground(new java.awt.Color(0, 173, 181));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReMarcaActionPerformed
        new VentanaAgregarEliminarMarca().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReMarcaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        new VentanaSesion().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModeloActionPerformed
        new VentanaAgregarEliminarModelo().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonModeloActionPerformed

    private void jButtonReEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReEmpleadosActionPerformed
        new VentanaRegistrarEmpleado().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReEmpleadosActionPerformed

    private void jButtonReClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReClienteActionPerformed
        new VentanaRegistrarCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReClienteActionPerformed

    private void jButtonReVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReVehiculoActionPerformed
        new VentanaRegistrarVehiculoCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReVehiculoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarDetalle;
    private javax.swing.JButton jButtonConsultarHistorial;
    private javax.swing.JButton jButtonModelo;
    private javax.swing.JButton jButtonReCliente;
    private javax.swing.JButton jButtonReEmpleados;
    private javax.swing.JButton jButtonReMarca;
    private javax.swing.JButton jButtonReServicio;
    private javax.swing.JButton jButtonReVehiculo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoBotones;
    private javax.swing.JLabel jLabelFondoInstrucciones;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
